/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class uk_ac_uws_danielszabo_automodera_common_service_hashing_RustPHash */

#ifndef _Included_uk_ac_uws_danielszabo_automodera_common_service_hashing_RustPHash
#define _Included_uk_ac_uws_danielszabo_automodera_common_service_hashing_RustPHash
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     uk_ac_uws_danielszabo_automodera_common_service_hashing_RustPHash
 * Method:    getSimilarityToFileWithHash
 * Signature: (Ljava/lang/String;Ljava/lang/String;)F
 */
JNIEXPORT jfloat JNICALL Java_uk_ac_uws_danielszabo_automodera_common_service_hashing_RustPHash_getSimilarityToFileWithHash
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     uk_ac_uws_danielszabo_automodera_common_service_hashing_RustPHash
 * Method:    getHashForFile
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_uk_ac_uws_danielszabo_automodera_common_service_hashing_RustPHash_getHashForFile
  (JNIEnv *, jclass, jstring);

/*
 * Class:     uk_ac_uws_danielszabo_automodera_common_service_hashing_RustPHash
 * Method:    getSimilarityScore
 * Signature: (Ljava/lang/String;Ljava/lang/String;)F
 */
JNIEXPORT jfloat JNICALL Java_uk_ac_uws_danielszabo_automodera_common_service_hashing_RustPHash_getSimilarityScore
  (JNIEnv *, jclass, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
