/*
 * Copyright (c) Daniel Szabo 2021.
 *
 * GitHub: https://github.com/szabodanika
 * Email: daniel.szabo99@outlook.com
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

package uk.ac.uws.danielszabo.common.model.hash;

import lombok.*;
import org.hibernate.Hibernate;

import javax.persistence.Entity;
import javax.persistence.Id;
import javax.xml.bind.annotation.*;
import java.util.Objects;

@Getter
@Setter
@ToString
@RequiredArgsConstructor
@NoArgsConstructor
@XmlRootElement
@XmlAccessorType(XmlAccessType.FIELD)
@Entity
public class Topic {
  // unique identifier for this topic
  @Id @XmlID @XmlAttribute @NonNull private String id;

  // display name
  @NonNull private String name;

  //  @ManyToMany(mappedBy = "topicList")
  //  @NonNull
  //  //  @XmlIDREF
  //  //  @XmlElementWrapper(name = "hashCollectionList")
  //  //  @XmlElement(name = "hashCollection")
  //  @ToString.Exclude
  //  @XmlTransient
  //  private List<HashCollection> hashCollectionList;

  // auto-generated by IntelliJ

  @Override
  public boolean equals(Object o) {
    if (this == o)
      return true;
    if (o == null || Hibernate.getClass(this) != Hibernate.getClass(o))
      return false;
    Topic topic = (Topic) o;
    return id != null && Objects.equals(id, topic.id);
  }

  @Override
  public int hashCode() {
    return getClass().hashCode();
  }
}
